class AIService:
    # TODO: Wire these methods to NestyAI once auth, model selection, retries, and audit logging are designed.
    def generate_customer(self) -> str:
        return "Placeholder customer generated by deterministic local logic."

    def generate_negotiation_reply(self) -> str:
        return "Placeholder negotiation reply. Real NestyAI integration is intentionally disabled."

    def generate_inspection_report(self) -> str:
        return "Placeholder inspection report based on revealed local test bench metrics."

    def generate_review(self) -> str:
        return "Placeholder customer review. Future versions can personalize this through NestyAI."

    def generate_market_event_proposal(self, context: dict) -> dict:
        # TODO: Wire to NestyAI when AI_MARKET_EVENTS_ENABLED is true.
        return {
            "event_type": "AI_DATACENTER_DEMAND",
            "title": "AI Server Memory Rush (AI Proposed)",
            "summary": "Datacenter buyers are absorbing high-capacity RAM and SSD stock, pushing local retail prices upward.",
            "severity": 4,
            "affected_category": "RAM",
            "affected_brand_slug": None,
            "affected_origin_code": None,
            "affected_currency": None,
            "affected_product_id": None,
            "price_multiplier": 2.1,
            "demand_delta": 25,
            "supply_delta": -15,
            "reliability_delta": 0,
            "quality_risk_delta": 0,
            "duration_days": 7
        }

