from enum import Enum


class HardwareCategory(str, Enum):
    CPU = "CPU"
    GPU = "GPU"
    RAM = "RAM"
    SSD = "SSD"
    STORAGE = "STORAGE"
    PSU = "PSU"
    MOTHERBOARD = "MOTHERBOARD"
    CASE = "CASE"
    COOLER = "COOLER"
    WATER_COOLING = "WATER_COOLING"
    MONITOR = "MONITOR"
    OTHER = "OTHER"


class BrandCategoryName(str, Enum):
    CPU = "CPU"
    GPU = "GPU"
    MOTHERBOARD = "MOTHERBOARD"
    RAM = "RAM"
    STORAGE = "STORAGE"
    PSU = "PSU"
    CASE = "CASE"
    COOLER = "COOLER"
    WATER_COOLING = "WATER_COOLING"
    MONITOR = "MONITOR"
    OTHER = "OTHER"


class BrandType(str, Enum):
    CHIP_VENDOR = "CHIP_VENDOR"
    BOARD_PARTNER = "BOARD_PARTNER"
    MEMORY_STORAGE = "MEMORY_STORAGE"
    PSU_CASE_COOLING = "PSU_CASE_COOLING"
    CASE_COOLING = "CASE_COOLING"
    RETAILER = "RETAILER"
    OTHER = "OTHER"


class MarketTier(str, Enum):
    PREMIUM = "PREMIUM"
    MAINSTREAM = "MAINSTREAM"
    VALUE = "VALUE"
    BUDGET = "BUDGET"
    GRAY_MARKET = "GRAY_MARKET"
    INDUSTRIAL = "INDUSTRIAL"
    UNKNOWN = "UNKNOWN"


class ShopUpgradeCategory(str, Enum):
    STORAGE = "STORAGE"
    TEST_BENCH = "TEST_BENCH"
    REFURBISH = "REFURBISH"
    SUPPLIER = "SUPPLIER"
    RESALE = "RESALE"
    WARRANTY = "WARRANTY"
    STAFF = "STAFF"
    CUSTOMER = "CUSTOMER"
    MARKET = "MARKET"
    OPERATIONS = "OPERATIONS"


class ShopUpgradeStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    PURCHASED = "PURCHASED"
    LOCKED = "LOCKED"


class StaffRole(str, Enum):
    SALES = "SALES"
    MARKETING = "MARKETING"
    TECHNICIAN = "TECHNICIAN"
    REPAIR_SPECIALIST = "REPAIR_SPECIALIST"
    PROCUREMENT = "PROCUREMENT"
    WARRANTY_SUPPORT = "WARRANTY_SUPPORT"
    MARKET_ANALYST = "MARKET_ANALYST"
    OPERATIONS = "OPERATIONS"


class StaffStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    BUSY = "BUSY"
    RESTING = "RESTING"
    INACTIVE = "INACTIVE"


class StaffTrait(str, Enum):
    METICULOUS = "METICULOUS"
    FAST_HANDS = "FAST_HANDS"
    SMOOTH_TALKER = "SMOOTH_TALKER"
    BARGAIN_HUNTER = "BARGAIN_HUNTER"
    HONEST_ADVISOR = "HONEST_ADVISOR"
    OVERCONFIDENT = "OVERCONFIDENT"
    CAREFUL_TESTER = "CAREFUL_TESTER"
    RGB_ADDICT = "RGB_ADDICT"
    DAMAGE_CONTROL = "DAMAGE_CONTROL"
    MARKET_SENSE = "MARKET_SENSE"


class StaffTaskType(str, Enum):
    CUSTOMER_CONSULT = "CUSTOMER_CONSULT"
    TEST_BENCH = "TEST_BENCH"
    REFURBISH = "REFURBISH"
    RESALE = "RESALE"
    WARRANTY = "WARRANTY"
    PROCUREMENT = "PROCUREMENT"
    MARKET_ANALYSIS = "MARKET_ANALYSIS"
    OPERATIONS = "OPERATIONS"


class ConditionType(str, Enum):
    NEW = "NEW"
    OPEN_BOX = "OPEN_BOX"
    USED = "USED"
    REFURBISHED = "REFURBISHED"
    DEFECTIVE = "DEFECTIVE"
    FOR_PARTS = "FOR_PARTS"


class InventoryStatus(str, Enum):
    UNTESTED = "UNTESTED"
    BASIC_CHECKED = "BASIC_CHECKED"
    BENCHMARKED = "BENCHMARKED"
    STRESS_TESTED = "STRESS_TESTED"
    FULLY_INSPECTED = "FULLY_INSPECTED"
    REFURBISHED = "REFURBISHED"
    READY_FOR_SALE = "READY_FOR_SALE"
    RESERVED = "RESERVED"
    INSTALLED_IN_BUILD = "INSTALLED_IN_BUILD"
    SOLD = "SOLD"
    WARRANTY_RETURN = "WARRANTY_RETURN"
    DEFECTIVE = "DEFECTIVE"
    FOR_PARTS = "FOR_PARTS"
    MINING_USE = "MINING_USE"
    RETIRED = "RETIRED"


class Grade(str, Enum):
    A_PLUS = "A_PLUS"
    A = "A"
    B = "B"
    C = "C"
    D = "D"
    F = "F"
    UNKNOWN = "UNKNOWN"


class InventorySource(str, Enum):
    SUPPLIER = "SUPPLIER"
    TRADE_IN = "TRADE_IN"
    USED_MARKET = "USED_MARKET"
    RETURN = "RETURN"
    OTHER = "OTHER"


class TestType(str, Enum):
    BASIC_CHECK = "BASIC_CHECK"
    BENCHMARK = "BENCHMARK"
    STRESS_TEST = "STRESS_TEST"
    FULL_INSPECTION = "FULL_INSPECTION"


class SupplierType(str, Enum):
    OFFICIAL_DISTRIBUTOR = "OFFICIAL_DISTRIBUTOR"
    USED_MARKET = "USED_MARKET"
    WHOLESALE = "WHOLESALE"
    OTHER = "OTHER"


class SupplierTier(str, Enum):
    OFFICIAL_DISTRIBUTOR = "OFFICIAL_DISTRIBUTOR"
    WHOLESALE = "WHOLESALE"
    IMPORTER = "IMPORTER"
    GRAY_MARKET = "GRAY_MARKET"
    USED_MARKET = "USED_MARKET"
    OTHER = "OTHER"



class PurchaseOrderStatus(str, Enum):
    DRAFT = "DRAFT"
    ORDERED = "ORDERED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"


class CustomerArchetype(str, Enum):
    GAMER = "GAMER"
    CREATOR = "CREATOR"
    OFFICE = "OFFICE"
    BUDGET_BUYER = "BUDGET_BUYER"
    TECH_NERD = "TECH_NERD"
    BUSINESS = "BUSINESS"
    SELLER = "SELLER"


class KnowledgeLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RiskTolerance(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RequestType(str, Enum):
    BUILD_PC = "BUILD_PC"
    BUY_COMPONENT = "BUY_COMPONENT"
    SELL_USED_PART = "SELL_USED_PART"
    UPGRADE_PC = "UPGRADE_PC"
    REPAIR = "REPAIR"


class CustomerRequestStatus(str, Enum):
    NEW = "NEW"
    IN_CONSULTATION = "IN_CONSULTATION"
    QUOTED = "QUOTED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"


class CustomerConversationStatus(str, Enum):
    OPEN = "OPEN"
    WAITING_FOR_PLAYER = "WAITING_FOR_PLAYER"
    WAITING_FOR_CUSTOMER = "WAITING_FOR_CUSTOMER"
    QUOTE_PROPOSED = "QUOTE_PROPOSED"
    READY_TO_ORDER = "READY_TO_ORDER"
    CLOSED_WON = "CLOSED_WON"
    CLOSED_LOST = "CLOSED_LOST"
    ARCHIVED = "ARCHIVED"


class CustomerConversationStage(str, Enum):
    NEW_REQUEST = "NEW_REQUEST"
    NEEDS_CONSULTATION = "NEEDS_CONSULTATION"
    QUALIFYING_NEEDS = "QUALIFYING_NEEDS"
    DISCUSSING_USED_PARTS = "DISCUSSING_USED_PARTS"
    QUOTE_BUILDING = "QUOTE_BUILDING"
    QUOTE_SENT = "QUOTE_SENT"
    NEGOTIATING = "NEGOTIATING"
    READY_TO_ORDER = "READY_TO_ORDER"
    CLOSED = "CLOSED"


class ConversationMessageSender(str, Enum):
    CUSTOMER = "CUSTOMER"
    PLAYER = "PLAYER"
    STAFF = "STAFF"
    SYSTEM = "SYSTEM"


class ConversationMessageType(str, Enum):
    TEXT = "TEXT"
    SYSTEM_NOTE = "SYSTEM_NOTE"
    QUICK_REPLY = "QUICK_REPLY"
    QUOTE_ATTACHMENT = "QUOTE_ATTACHMENT"
    ACTION_EVENT = "ACTION_EVENT"


class ConversationActionType(str, Enum):
    ASK_BUDGET = "ASK_BUDGET"
    ASK_USE_CASE = "ASK_USE_CASE"
    ASK_USED_PARTS = "ASK_USED_PARTS"
    RECOMMEND_VALUE_BUILD = "RECOMMEND_VALUE_BUILD"
    RECOMMEND_ALL_NEW_BUILD = "RECOMMEND_ALL_NEW_BUILD"
    EXPLAIN_WARRANTY_RISK = "EXPLAIN_WARRANTY_RISK"
    ASSIGN_SALES_STAFF = "ASSIGN_SALES_STAFF"
    GENERATE_QUOTE = "GENERATE_QUOTE"
    SEND_QUOTE = "SEND_QUOTE"
    CONVERT_TO_ORDER = "CONVERT_TO_ORDER"
    CLOSE_WON = "CLOSE_WON"
    CLOSE_LOST = "CLOSE_LOST"


class OrderStatus(str, Enum):
    DRAFT = "DRAFT"
    QUOTED = "QUOTED"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    TESTING = "TESTING"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
    WARRANTY = "WARRANTY"


class QuoteStatus(str, Enum):
    DRAFT = "DRAFT"
    PRESENTED = "PRESENTED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CONVERTED_TO_ORDER = "CONVERTED_TO_ORDER"


class QuoteItemSource(str, Enum):
    INVENTORY = "INVENTORY"
    CATALOG_PLACEHOLDER = "CATALOG_PLACEHOLDER"
    SUPPLIER_NEEDED = "SUPPLIER_NEEDED"


class OrderFulfillmentEventType(str, Enum):
    BUILD_STARTED = "BUILD_STARTED"
    BUILD_TESTED = "BUILD_TESTED"
    DELIVERED = "DELIVERED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    CANCELLED = "CANCELLED"


class WarrantyClaimStatus(str, Enum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    DIAGNOSING = "DIAGNOSING"
    AWAITING_DECISION = "AWAITING_DECISION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RESOLVED = "RESOLVED"
    CANCELLED = "CANCELLED"
    IN_REPAIR = "IN_REPAIR"
    REPLACED = "REPLACED"
    REFUNDED = "REFUNDED"
    RMA_SUBMITTED = "RMA_SUBMITTED"
    RMA_COMPLETED = "RMA_COMPLETED"
    CLOSED = "CLOSED"


class WarrantyClaimType(str, Enum):
    DOA = "DOA"
    OVERHEATING = "OVERHEATING"
    RANDOM_CRASH = "RANDOM_CRASH"
    PERFORMANCE_ISSUE = "PERFORMANCE_ISSUE"
    FAN_NOISE = "FAN_NOISE"
    STORAGE_FAILURE = "STORAGE_FAILURE"
    ARTIFACTING = "ARTIFACTING"
    POWER_ISSUE = "POWER_ISSUE"
    CUSTOMER_DAMAGE = "CUSTOMER_DAMAGE"
    COSMETIC_COMPLAINT = "COSMETIC_COMPLAINT"
    OTHER = "OTHER"


class WarrantyClaimReason(str, Enum):
    NO_DISPLAY = "NO_DISPLAY"
    CRASHING = "CRASHING"
    OVERHEATING = "OVERHEATING"
    ARTIFACTING = "ARTIFACTING"
    NOISY_FAN = "NOISY_FAN"
    PERFORMANCE_ISSUE = "PERFORMANCE_ISSUE"
    RANDOM_SHUTDOWN = "RANDOM_SHUTDOWN"
    DOA = "DOA"
    OTHER = "OTHER"


class WarrantyResolutionType(str, Enum):
    REPAIR = "REPAIR"
    REPLACE = "REPLACE"
    REFUND = "REFUND"
    REJECT = "REJECT"
    GOODWILL_CREDIT = "GOODWILL_CREDIT"


class WarrantyEventType(str, Enum):
    CLAIM_OPENED = "CLAIM_OPENED"
    DIAGNOSIS_STARTED = "DIAGNOSIS_STARTED"
    DIAGNOSIS_COMPLETED = "DIAGNOSIS_COMPLETED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REPAIR_STARTED = "REPAIR_STARTED"
    REPAIR_COMPLETED = "REPAIR_COMPLETED"
    REPLACEMENT_ISSUED = "REPLACEMENT_ISSUED"
    REFUND_ISSUED = "REFUND_ISSUED"
    RMA_SUBMITTED = "RMA_SUBMITTED"
    RMA_COMPLETED = "RMA_COMPLETED"
    CLAIM_CLOSED = "CLAIM_CLOSED"


class ProductPriceType(str, Enum):
    MSRP = "MSRP"
    LOCAL_RETAIL = "LOCAL_RETAIL"
    USED_MARKET = "USED_MARKET"
    SUPPLIER_COST = "SUPPLIER_COST"
    IMPORT_COST = "IMPORT_COST"
    CLEARANCE = "CLEARANCE"
    ESTIMATED = "ESTIMATED"


class ProductPriceConfidence(str, Enum):
    OFFICIAL = "OFFICIAL"
    RETAILER = "RETAILER"
    SUPPLIER = "SUPPLIER"
    MANUAL = "MANUAL"
    ESTIMATED = "ESTIMATED"


class MarketEventType(str, Enum):
    MINING_BOOM = "MINING_BOOM"
    MINING_CRASH = "MINING_CRASH"
    AI_DATACENTER_DEMAND = "AI_DATACENTER_DEMAND"
    NEW_GPU_GENERATION = "NEW_GPU_GENERATION"
    SUPPLY_SHORTAGE = "SUPPLY_SHORTAGE"
    OVERSUPPLY_CLEARANCE = "OVERSUPPLY_CLEARANCE"
    ESPORTS_SEASON = "ESPORTS_SEASON"
    BACK_TO_SCHOOL = "BACK_TO_SCHOOL"
    DEFECTIVE_BATCH_RUMOR = "DEFECTIVE_BATCH_RUMOR"
    DRIVER_DRAMA = "DRIVER_DRAMA"
    TAIWAN_SUPPLY_DELAY = "TAIWAN_SUPPLY_DELAY"
    CHINA_BUDGET_PARTS_FLOOD = "CHINA_BUDGET_PARTS_FLOOD"
    CURRENCY_SHOCK = "CURRENCY_SHOCK"
    RANDOM_DEMAND_SPIKE = "RANDOM_DEMAND_SPIKE"
    RANDOM_PRICE_CRASH = "RANDOM_PRICE_CRASH"


class MarketEventGenerationSource(str, Enum):
    RULE = "RULE"
    AI_PROPOSED = "AI_PROPOSED"
    AI_FALLBACK = "AI_FALLBACK"
    MANUAL = "MANUAL"


class UsedPartListingStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    NEGOTIATING = "NEGOTIATING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class UsedPartNegotiationStatus(str, Enum):
    OPEN = "OPEN"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CLOSED = "CLOSED"


class NegotiationSender(str, Enum):
    PLAYER = "PLAYER"
    SELLER = "SELLER"
    SYSTEM = "SYSTEM"


class RefurbishActionType(str, Enum):
    CLEAN_DUST = "CLEAN_DUST"
    REPASTE = "REPASTE"
    REPLACE_FAN = "REPLACE_FAN"
    REPLACE_THERMAL_PADS = "REPLACE_THERMAL_PADS"
    FIRMWARE_FLASH = "FIRMWARE_FLASH"
    BASIC_REPAIR = "BASIC_REPAIR"
    DEEP_DIAGNOSTIC = "DEEP_DIAGNOSTIC"
    STRESS_VALIDATION = "STRESS_VALIDATION"
    COSMETIC_CLEANUP = "COSMETIC_CLEANUP"


class RefurbishResultStatus(str, Enum):
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    BLOCKED = "BLOCKED"


class ResaleListingStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    SOLD = "SOLD"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class ResaleBuyerOfferStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
